const nodemailer = require('nodemailer');
const dotenv = require('dotenv');

dotenv.config();

class EmailSender {
  constructor() {
    // Skip email setup if no valid password provided
    if (!process.env.EMAIL_PASS || process.env.EMAIL_PASS === 'your-gmail-app-password' || process.env.EMAIL_PASS === '') {
      console.log('⚠️ Email disabled: No valid EMAIL_PASS provided');
      this.disabled = true;
      this.alertEmail = process.env.ALERT_EMAIL;
      return;
    }
    
    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    });
    
    this.alertEmail = process.env.ALERT_EMAIL;
  }

  async sendExpansionAlert(prediction) {
    if (this.disabled) {
      console.log('📧 Email disabled - Expansion alert logged:', prediction.company_name);
      return { success: true, disabled: true };
    }
    
    try {
      const subject = `🚨 EXPANSION DETECTED: ${prediction.company_name} - ${prediction.location}`;
      
      const htmlContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px 10px 0 0;">
            <h1 style="margin: 0; font-size: 24px;">🚨 EXPANSION DETECTED</h1>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">IntelliSense Real Estate Intelligence</p>
          </div>
          
          <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 25px;">
              <h2 style="color: #333; margin: 0 0 15px 0; font-size: 20px;">${prediction.company_name}</h2>
              <div style="display: flex; align-items: center; margin-bottom: 10px;">
                <span style="background: ${prediction.confidence_score >= 90 ? '#28a745' : prediction.confidence_score >= 80 ? '#ffc107' : '#dc3545'}; color: white; padding: 4px 12px; border-radius: 20px; font-weight: bold; font-size: 14px;">
                  ${prediction.confidence_score}% Confidence
                </span>
              </div>
              <p style="color: #666; margin: 0;"><strong>Location:</strong> ${prediction.location}</p>
            </div>
            
            <div style="margin-bottom: 25px;">
              <h3 style="color: #333; margin: 0 0 10px 0;">Evidence</h3>
              <ul style="color: #666; padding-left: 20px;">
                ${prediction.evidence.map(item => `<li style="margin-bottom: 5px;">${item}</li>`).join('')}
              </ul>
            </div>
            
            <div style="margin-bottom: 25px;">
              <h3 style="color: #333; margin: 0 0 10px 0;">Timeline</h3>
              <p style="color: #666; margin: 0;">Estimated announcement in <strong>${prediction.timeline_days} days</strong></p>
            </div>
            
            <div style="background: #e3f2fd; padding: 20px; border-radius: 8px; border-left: 4px solid #2196f3;">
              <h3 style="color: #1976d2; margin: 0 0 10px 0;">Recommended Action</h3>
              <p style="color: #333; margin: 0; font-weight: 500;">${prediction.action_recommendation}</p>
            </div>
            
            <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
              <p style="color: #999; font-size: 12px; margin: 0;">
                Generated by IntelliSense at ${new Date().toLocaleString()}
              </p>
            </div>
          </div>
        </div>
      `;
      
      const textContent = `
🚨 EXPANSION DETECTED: ${prediction.company_name} - ${prediction.location}

Company: ${prediction.company_name}
Confidence: ${prediction.confidence_score}%
Location: ${prediction.location}
Timeline: ${prediction.timeline_days} days

Evidence:
${prediction.evidence.map(item => `• ${item}`).join('\n')}

Action: ${prediction.action_recommendation}

Generated by IntelliSense at ${new Date().toLocaleString()}
      `;

      const mailOptions = {
        from: process.env.EMAIL_USER,
        to: this.alertEmail,
        subject: subject,
        text: textContent,
        html: htmlContent
      };

      const result = await this.transporter.sendMail(mailOptions);
      console.log('📧 Alert email sent successfully:', result.messageId);
      
      return {
        success: true,
        messageId: result.messageId
      };
      
    } catch (error) {
      console.error('❌ Error sending email:', error);
      throw error;
    }
  }

  async sendDailyReport(stats) {
    if (this.disabled) {
      console.log('📧 Email disabled - Daily report logged:', stats);
      return { success: true, disabled: true };
    }
    
    try {
      const subject = `📊 IntelliSense Daily Report - ${new Date().toLocaleDateString()}`;
      
      const htmlContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: white; padding: 20px; border-radius: 10px 10px 0 0;">
            <h1 style="margin: 0; font-size: 24px;">📊 Daily Report</h1>
            <p style="margin: 5px 0 0 0; opacity: 0.9;">${new Date().toLocaleDateString()}</p>
          </div>
          
          <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 25px;">
              <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center;">
                <h3 style="color: #333; margin: 0 0 10px 0;">Permits Scraped</h3>
                <p style="font-size: 28px; font-weight: bold; color: #007bff; margin: 0;">${stats.permits}</p>
              </div>
              <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; text-align: center;">
                <h3 style="color: #333; margin: 0 0 10px 0;">Predictions Made</h3>
                <p style="font-size: 28px; font-weight: bold; color: #28a745; margin: 0;">${stats.predictions}</p>
              </div>
            </div>
            
            <div style="margin-bottom: 25px;">
              <h3 style="color: #333; margin: 0 0 15px 0;">System Status</h3>
              <div style="background: #d4edda; color: #155724; padding: 15px; border-radius: 8px; border-left: 4px solid #28a745;">
                <p style="margin: 0; font-weight: 500;">✅ All systems operational</p>
              </div>
            </div>
            
            <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
              <p style="color: #999; font-size: 12px; margin: 0;">
                IntelliSense Real Estate Intelligence System
              </p>
            </div>
          </div>
        </div>
      `;

      const mailOptions = {
        from: process.env.EMAIL_USER,
        to: this.alertEmail,
        subject: subject,
        html: htmlContent
      };

      const result = await this.transporter.sendMail(mailOptions);
      console.log('📧 Daily report sent successfully:', result.messageId);
      
      return {
        success: true,
        messageId: result.messageId
      };
      
    } catch (error) {
      console.error('❌ Error sending daily report:', error);
      throw error;
    }
  }

  async testConnection() {
    if (this.disabled) {
      console.log('⚠️ Email connection test skipped - Email disabled');
      return false;
    }
    
    try {
      await this.transporter.verify();
      console.log('✅ Email connection verified');
      return true;
    } catch (error) {
      console.error('❌ Email connection failed:', error);
      return false;
    }
  }
}

module.exports = EmailSender; 